"""Provider-neutral queue protocol."""

from typing import Protocol

from footballai_v2.execution.contracts import ExecutionJob


class JobQueue(Protocol):
    def enqueue(self, job: ExecutionJob) -> None: ...
    def claim(self, worker_id: str) -> ExecutionJob | None: ...
    def complete(self, job: ExecutionJob) -> None: ...
    def fail(self, job: ExecutionJob) -> None: ...
    def cancel(self, run_id: str) -> bool: ...
